package elvira.gui;

import javax.swing.JPanel;

import java.awt.Container;
import java.awt.Frame;
import javax.swing.JDialog;
import javax.swing.JLabel;
import java.awt.Dimension;
import java.awt.Rectangle;
import javax.swing.JComboBox;
import java.awt.GridBagLayout;
import javax.swing.JScrollPane;
import javax.swing.JTable;

import elvira.Bnet;
import elvira.Elvira;
import elvira.Link;

import java.awt.GridBagConstraints;
import java.util.ResourceBundle;
import javax.swing.JButton;

public class LinkPropertiesDialog extends JDialog {

	private static final long serialVersionUID = 1L;

	private JPanel jContentPane = null;

	private JLabel relationLabel = null;

	private JComboBox relationCombo = null;

	private JLabel constraintsLabel = null;

	private JPanel constraintsPanel = null;

	private JScrollPane constraintsScrollPane = null;

	private JTable constraintsTable = null;
	
	ResourceBundle menuBundle, dialogBundle, explanationBundle;
    
    Bnet bayesNet;
    Link link;
    
     public static String[] relationskind={"Produce", "Favorece", "Se diagnostica", "Es-un", "tiene", "otro", "Arco de revelación", ""};

	private JButton okButton = null;

	private JButton cancelButton = null;


	/**
	 * @param owner
	 */
	public LinkPropertiesDialog(Frame owner) {
	    super(owner);
        initialize();
        
        dialogBundle = Elvira.getElviraFrame().getDialogBundle();
	menuBundle = Elvira.getElviraFrame().getMenuBundle();
		int languaje=Elvira.getLanguaje();

	   	switch (languaje) {
		   case 0: explanationBundle = ResourceBundle.getBundle ("elvira/localize/Explanation_sp");
		                         break;
		   case 1: explanationBundle = ResourceBundle.getBundle ("elvira/localize/Explanation");
		                        break;
		}


		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		//setResizable(false);
		//setModal(true);
		setTitle(localize(dialogBundle,"LinkProperties.Title.label"));
		Container contentPane = getContentPane();
		contentPane.setLayout(null);
                //setSize(320,250);
		setSize(320,350);
		setVisible(false);
		//directedRadioButton.setText(localize(dialogBundle,
		//      "LinkProperties.Directed.label"));
		//directedRadioButton.setActionCommand("Directed");
		//contentPane.add(directedRadioButton);
		//directedRadioButton.setBounds(60,24,72,36);
		//undirectedRadioButton.setText(localize(dialogBundle,
		 //     "LinkProperties.Undirected.label"));
		//undirectedRadioButton.setActionCommand("Undirected");
		//undirectedRadioButton.setEnabled(false);
		//contentPane.add(undirectedRadioButton);
		//undirectedRadioButton.setBounds(192,24,108,36);

		//nameLabel.setText(localize(explanationBundle,"Name.label"));
		//contentPane.add(nameLabel);
		//nameLabel.setBounds(56,70,48,24);
		//nameTextField.setEditable(true);
		//contentPane.add(nameTextField);
		//nameTextField.setBounds(108,70,168,24);
		
                      
                      relationLabel.setText(localize(explanationBundle,"RelationKind.label"));
                      
                      for (String auxRelKind:relationskind){
                        relationCombo.addItem(auxRelKind);
                      }
		//contentPane.add(relationLabel);
		//relationLabel.setBounds(12,100,96,24);
		//relationCombo.setBounds(108,100,168,24);
		//relationCombo.setEditable(false);
		//contentPane.add(relationCombo);


//		parentLabel.setText(localize(dialogBundle,
//		      "LinkProperties.Parent.label"));
//		contentPane.add(parentLabel);
//		parentLabel.setBounds(48,134,60,24);
//		contentPane.add(parentComboBox);
//		parentComboBox.setBounds(108,134,168,24);
//		childLabel.setText(localize(dialogBundle,
//		      "LinkProperties.Child.label"));
//		contentPane.add(childLabel);
//		childLabel.setBounds(48,164,60,26);
//		contentPane.add(childComboBox);
//		childComboBox.setBounds(108,164,168,25);
		
		
		//javax.swing.JLabel constraintsLabel = new javax.swing.JLabel();
		constraintsLabel.setText(
			      localize(dialogBundle,"LinkProperties.Constraints.label"));
		//constraintsLabel.setBounds(48,194,96,24);
		//contentPane.add(constraintsLabel);
		
		
	/*	GridBagLayout gridbag = new GridBagLayout();
	    GridBagConstraints gridbagCons = new GridBagConstraints();
		gridbagCons = EditVariableDialog.setGridBagConstraints (0,2,4,3,1.5,1.0);
		gridbag.setConstraints(tablePanel, c);*/
		
		
		//Components for the constraints table
                //constraintsPanel.setLayout(new BorderLayout(0,0));
		//constraintsPanel.setBounds(1,90,571,220);
		//constraintsScrollPane.setOpaque(true);
		//constraintsPanel.add(BorderLayout.CENTER,constraintsScrollPane);
		//constraintsScrollPane.setBounds(0,0,570,219);
		//constraintsTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
		//constraintsScrollPane.getViewport().add(constraintsTable);
		//constraintsTable.setBounds(0,0,0,0);
		//contentPane.add(constraintsPanel);
		
		okButton.setText("OK");
		okButton.setActionCommand("OK");
		//contentPane.add(okButton);
		//okButton.setBounds(60,230,100,36);
		cancelButton.setText(localize(dialogBundle,
		      "Cancel.label"));
		cancelButton.setActionCommand("Cancel");
		//contentPane.add(cancelButton);
		//cancelButton.setBounds(192,230,100,36);
		//}}

		//linkTypeGroup.add(directedRadioButton);
		//linkTypeGroup.add(undirectedRadioButton);

                bayesNet = ((NetworkFrame) Elvira.getElviraFrame().getCurrentNetworkFrame()).getEditorPanel().getBayesNet();

		setLocationRelativeTo(Elvira.getElviraFrame());

		//{{REGISTER_LISTENERS
		//SymAction lSymAction = new SymAction();
                //NSymAction kSymAction = new NSymAction();
                //directedRadioButton.registerKeyboardAction(kSymAction, javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE,0,false),JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
                //undirectedRadioButton.registerKeyboardAction(kSymAction, javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE,0,false),JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
                //nameTextField.registerKeyboardAction(kSymAction, javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE,0,false),JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
                //parentComboBox.registerKeyboardAction(kSymAction, javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE,0,false),JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
                //childComboBox.registerKeyboardAction(kSymAction, javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE,0,false),JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
                //relationCombo.registerKeyboardAction(kSymAction, javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE,0,false),JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
                //okButton.registerKeyboardAction(kSymAction, javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE,0,false),JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
                //cancelButton.registerKeyboardAction(kSymAction, javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE,0,false),JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
		//okButton.addActionListener(lSymAction);
                //okButton.registerKeyboardAction(lSymAction, javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER,0,false),JComponent.WHEN_FOCUSED);
		//cancelButton.addActionListener(lSymAction);
                //cancelButton.registerKeyboardAction(lSymAction, javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER,0,false),JComponent.WHEN_FOCUSED);
	}

	      public String localize (ResourceBundle bundle, String name) {
      return ElviraFrame.localize(bundle, name);
   }

	public LinkPropertiesDialog(Link link, boolean propertiesEditable) {
		// TODO Auto-generated constructor stub
    	this();
		this.link=link;
	}

	public LinkPropertiesDialog() {
		// TODO Auto-generated constructor stub
	}

	/**
	 * This method initializes this
	 * 
	 * @return void
	 */
	private void initialize() {
		this.setSize(662, 451);
		this.setContentPane(getJContentPane());
	}

	/**
	 * This method initializes jContentPane
	 * 
	 * @return javax.swing.JPanel
	 */
	private JPanel getJContentPane() {
		if (jContentPane == null) {
			constraintsLabel = new JLabel();
			constraintsLabel.setBounds(new Rectangle(118, 110, 96, 24));
			constraintsLabel.setText("JLabel");
			relationLabel = new JLabel();
			relationLabel.setBounds(new Rectangle(118, 54, 96, 24));
			relationLabel.setText("JLabel");
			jContentPane = new JPanel();
			jContentPane.setLayout(null);
			jContentPane.setPreferredSize(new Dimension(320, 350));
			jContentPane.add(relationLabel, null);
			jContentPane.add(getRelationCombo(), null);
			jContentPane.add(constraintsLabel, null);
			jContentPane.add(getConstraintsPanel(), null);
			jContentPane.add(getOkButton(), null);
			jContentPane.add(getCancelButton(), null);
		}
		return jContentPane;
	}

	/**
	 * This method initializes relationCombo	
	 * 	
	 * @return javax.swing.JComboBox	
	 */
	private JComboBox getRelationCombo() {
		if (relationCombo == null) {
			relationCombo = new JComboBox();
			relationCombo.setBounds(new Rectangle(316, 54, 168, 24));
			relationCombo.setName("sdfs");
		}
		return relationCombo;
	}

	/**
	 * This method initializes constraintsPanel	
	 * 	
	 * @return javax.swing.JPanel	
	 */
	private JPanel getConstraintsPanel() {
		if (constraintsPanel == null) {
			GridBagConstraints gridBagConstraints = new GridBagConstraints();
			gridBagConstraints.fill = GridBagConstraints.BOTH;
			gridBagConstraints.gridy = 0;
			gridBagConstraints.weightx = 1.0;
			gridBagConstraints.weighty = 1.0;
			gridBagConstraints.gridx = 0;
			constraintsPanel = new JPanel();
			constraintsPanel.setLayout(new GridBagLayout());
			constraintsPanel.setBounds(new Rectangle(122, 184, 250, 95));
			constraintsPanel.add(getConstraintsScrollPane(), gridBagConstraints);
		}
		return constraintsPanel;
	}

	/**
	 * This method initializes constraintsScrollPane	
	 * 	
	 * @return javax.swing.JScrollPane	
	 */
	private JScrollPane getConstraintsScrollPane() {
		if (constraintsScrollPane == null) {
			constraintsScrollPane = new JScrollPane();
			constraintsScrollPane.setViewportView(getConstraintsTable());
		}
		return constraintsScrollPane;
	}

	/**
	 * This method initializes constraintsTable	
	 * 	
	 * @return javax.swing.JTable	
	 */
	private JTable getConstraintsTable() {
		if (constraintsTable == null) {
			constraintsTable = new JTable();
		}
		return constraintsTable;
	}

	/**
	 * This method initializes okButton	
	 * 	
	 * @return javax.swing.JButton	
	 */
	private JButton getOkButton() {
		if (okButton == null) {
			okButton = new JButton();
			okButton.setBounds(new Rectangle(151, 335, 100, 36));
		}
		return okButton;
	}

	/**
	 * This method initializes cancelButton	
	 * 	
	 * @return javax.swing.JButton	
	 */
	private JButton getCancelButton() {
		if (cancelButton == null) {
			cancelButton = new JButton();
			cancelButton.setBounds(new Rectangle(402, 335, 100, 36));
		}
		return cancelButton;
	}

}  //  @jve:decl-index=0:visual-constraint="10,10"
