/* Generated By:JavaCC: Do not edit this line. BayesNetConstants.java */

package elvira.parser;

public interface BayesNetConstants {

  int EOF = 0;
  int NETWORK = 4;
  int TITLE = 5;
  int COMMENT = 6;
  int WORD = 7;
  int LETTER = 8;
  int DIGIT = 9;
  int DECIMAL_LITERAL = 10;
  int EQUAL = 11;
  int STRING = 12;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "<token of kind 3>",
    "\"network\"",
    "\"title\"",
    "\"comment\"",
    "<WORD>",
    "<LETTER>",
    "<DIGIT>",
    "<DECIMAL_LITERAL>",
    "\"=\"",
    "<STRING>",
    "\"}\"",
    "\"{\"",
    "\";\"",
  };

}
