/* Generated By:JavaCC: Do not edit this line. DataBaseParseConstants.java */
package elvira.parser;

public interface DataBaseParseConstants {

  int EOF = 0;
  int DATABASE = 4;
  int TITLE = 5;
  int COMMENT = 6;
  int AUTHOR = 7;
  int WHOCHANGED = 8;
  int WHENCHANGED = 9;
  int VERSION = 10;
  int LOCKED = 11;
  int CONSISTENCY = 12;
  int NODE = 13;
  int FINITE = 14;
  int CONTINUOUS = 15;
  int NODETYPE = 16;
  int NODEKIND = 17;
  int NUMSTATES = 18;
  int POSX = 19;
  int POSY = 20;
  int STATES = 21;
  int VALUES = 22;
  int CASES = 23;
  int DEFVALUE = 24;
  int EVERY = 25;
  int RELATION = 26;
  int MEMORY = 27;
  int CASESNUMBER = 28;
  int MIN = 29;
  int MAX = 30;
  int CHANCE = 31;
  int DECISION = 32;
  int UTILITY = 33;
  int RELEVANCE = 34;
  int PURPOSE = 35;
  int VALUENOTDEF = 36;
  int BOOLEAN = 37;
  int TRUE = 38;
  int FALSE = 39;
  int OPEN_PAREN = 40;
  int CLOSE_PAREN = 41;
  int COMMA = 42;
  int OPEN_COR = 43;
  int CLOSE_COR = 44;
  int PARAMETER_WORD = 45;
  int WORD = 46;
  int LETTER = 47;
  int DIGIT = 48;
  int DECIMAL_LITERAL = 49;
  int INTEGER = 50;
  int FLOATSCI = 51;
  int FLOAT = 52;
  int EQUAL = 53;
  int STRINGDECIMAL = 54;
  int STRING = 55;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "<token of kind 3>",
    "\"data-base\"",
    "\"title\"",
    "\"comment\"",
    "\"author\"",
    "\"whochanged\"",
    "\"whenchanged\"",
    "\"version\"",
    "\"locked\"",
    "\"consistency-properties\"",
    "\"node\"",
    "\"finite-states\"",
    "\"continuous\"",
    "\"type-of-variable\"",
    "\"kind-of-node\"",
    "\"num-states\"",
    "\"pos_x\"",
    "\"pos_y\"",
    "\"states\"",
    "\"values\"",
    "\"cases\"",
    "\"default\"",
    "\"every\"",
    "\"relation\"",
    "\"memory\"",
    "\"number-of-cases\"",
    "\"min\"",
    "\"max\"",
    "\"chance\"",
    "\"decision\"",
    "\"utility\"",
    "\"relevance\"",
    "\"purpose\"",
    "\"?\"",
    "<BOOLEAN>",
    "\"true\"",
    "\"false\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "<PARAMETER_WORD>",
    "<WORD>",
    "<LETTER>",
    "<DIGIT>",
    "<DECIMAL_LITERAL>",
    "<INTEGER>",
    "<FLOATSCI>",
    "<FLOAT>",
    "\"=\"",
    "<STRINGDECIMAL>",
    "<STRING>",
    "\"}\"",
    "\"{\"",
    "\";\"",
  };

}
