/* Generated By:JavaCC: Do not edit this line. Hugin2ElvParseConstants.java */
package elvira.translator.hugin2elv;

public interface Hugin2ElvParseConstants {

  int EOF = 0;
  int NETWORK = 3;
  int NAME = 4;
  int NODE = 5;
  int UTILITY = 6;
  int DECISION = 7;
  int LABEL = 8;
  int NODE_SIZE = 9;
  int STATES = 10;
  int POSITION = 11;
  int POTENTIAL = 12;
  int DATA = 13;
  int OPEN_PAREN = 14;
  int CLOSE_PAREN = 15;
  int COMMA = 16;
  int OPEN_COR = 17;
  int CLOSE_COR = 18;
  int BAR = 19;
  int DECIMAL_LITERAL = 20;
  int INTEGER = 21;
  int FLOATSCI = 22;
  int FLOAT = 23;
  int WORD = 24;
  int LETTER = 25;
  int DIGIT = 26;
  int EQUAL = 27;
  int STRINGDECIMAL = 28;
  int STRING = 29;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "\"net\"",
    "\"name\"",
    "\"node\"",
    "\"utility\"",
    "\"decision\"",
    "\"label\"",
    "\"node_size\"",
    "\"states\"",
    "\"position\"",
    "\"potential\"",
    "\"data\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\"|\"",
    "<DECIMAL_LITERAL>",
    "<INTEGER>",
    "<FLOATSCI>",
    "<FLOAT>",
    "<WORD>",
    "<LETTER>",
    "<DIGIT>",
    "\"=\"",
    "<STRINGDECIMAL>",
    "<STRING>",
    "\";\"",
    "\"{\"",
    "\"}\"",
  };

}
