/* Generated By:JavaCC: Do not edit this line. XBif2ElvParseConstants.java */
package elvira.translator.xbif2elv;

public interface XBif2ElvParseConstants {

  int EOF = 0;
  int VERSION = 5;
  int EQUAL = 6;
  int TYPE = 7;
  int XBIF = 8;
  int XBIF_END = 9;
  int NETWORK = 10;
  int NETWORK_END = 11;
  int NAME = 12;
  int NAME_END = 13;
  int VARIABLE = 14;
  int VARIABLE_END = 15;
  int VALUES = 16;
  int VALUES_END = 17;
  int OBSERVED = 18;
  int OBSERVED_END = 19;
  int PROBABILITY = 20;
  int PROBABILITY_END = 21;
  int FOR = 22;
  int FOR_END = 23;
  int GIVEN = 24;
  int GIVEN_END = 25;
  int TABLE = 26;
  int TABLE_END = 27;
  int FLOATSCI = 28;
  int FLOAT = 29;
  int WORD = 30;
  int LETTER = 31;
  int DIGIT = 32;
  int STRINGDECIMAL = 33;
  int STRING = 34;
  int DECIMAL_LITERAL = 35;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "<token of kind 3>",
    "<token of kind 4>",
    "\"version\"",
    "\"=\"",
    "\"type\"",
    "<XBIF>",
    "\"</xbif>\"",
    "\"<network>\"",
    "\"</network>\"",
    "\"<name>\"",
    "\"</name>\"",
    "<VARIABLE>",
    "\"</variable>\"",
    "\"<values>\"",
    "\"</values>\"",
    "\"<observed>\"",
    "\"</observed>\"",
    "\"<probability>\"",
    "\"</probability>\"",
    "\"<for>\"",
    "\"</for>\"",
    "\"<given>\"",
    "\"</given>\"",
    "\"<table>\"",
    "\"</table>\"",
    "<FLOATSCI>",
    "<FLOAT>",
    "<WORD>",
    "<LETTER>",
    "<DIGIT>",
    "<STRINGDECIMAL>",
    "<STRING>",
    "<DECIMAL_LITERAL>",
  };

}
